FROM python:2.7
MAINTAINER David Li <legendarilylwq@gmail.com>

RUN pip install youtube-dl

COPY yt-download.sh /usr/app/yt-download.sh
COPY yt-get-title-size.sh /usr/app/yt-get-title-size.sh
RUN chmod +x /usr/app/yt-download.sh /usr/app/yt-get-title-size.sh

VOLUME ['/usr/app/video']

WORKDIR /usr/app/

CMD ["bash"]
